project_name: PapaZ810/glance

checksum:
  disable: true

builds:
  - binary: glance
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    goarm:
      - 7
    ldflags:
      - -s -w -X github.com/PapaZ810/glance/internal/glance.buildVersion={{ .Tag }}

archives:
  -
    name_template: "glance-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}"
    files:
      - nothing*
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - image_templates:
      - &amd64_image "{{ .ProjectName }}:{{ .Tag }}-amd64"
    build_flag_templates:
      - --platform=linux/amd64
    goarch: amd64
    use: buildx
    dockerfile: Dockerfile.goreleaser

docker_manifests:
  - name_template: "{{ .ProjectName }}:{{ .Tag }}"
    image_templates: &multiarch_images
      - *amd64_image
  - name_template: "{{ .ProjectName }}:latest"
    skip_push: auto
    image_templates: *multiarch_images
